site_name: Data Science

repo_name: RedGamer887/ds-course-notes
repo_url: https://github.com/RedGamer887/ds-course-notes

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: blue
      accent: pink
    - scheme: slate
      primary: blue
      accent: pink
nav:
  - Курс Data Science: index.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables